version: '3.8'

services:
  miner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    command: ["run-api"]
    environment:
      - DATABASE_HOSTNAME=postgres
    ports:
      - 8443:8080
    networks:
      - app-network
    restart: always

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=super_duper_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

    networks:
      - app-network
    restart: always


networks:
  app-network:
    name: app-network

