// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package repositories

import (
	"github.com/google/uuid"
)

type Author struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
}

type Movie struct {
	ID        int64
	MovieName string
}
